local mainPage = action_wheel:newPage()
action_wheel:setPage(mainPage)

local tglUnexpected = mainPage:newAction()
    :title("newExclusiveAnimation")
    :item("minecraft:gray_dye")
    :toggleItem("minecraft:lime_dye")
tglUnexpected:setOnToggle(function () customStates.newExclusiveAnimation = tglUnexpected:isToggled() end)

local tglHalo = mainPage:newAction()
    :title("tgl halo")
    :item("minecraft:gray_dye")
    :toggleItem("minecraft:lime_dye")
    :setToggled(true)
tglHalo:setOnToggle(function () pings.tglHalo(tglHalo:isToggled()) end)

local waveHand = mainPage:newAction()
    :title("wave hand")
    :item("minecraft:cookie")
    :setOnToggle(function () pings.waveHand() end)
